*"* use this source file for the definition and implementation of
*"* local helper classes, interface definitions and type
*"* declarations


CLASS lcl_input DEFINITION.
  PUBLIC SECTION.
    METHODS constructor.
    DATA mt_input TYPE zcl_advent2020_day10=>inttab.
ENDCLASS.


CLASS lcl_input IMPLEMENTATION.
  METHOD constructor.
    mt_input = VALUE #(
            ( |8| )
            ( |40| )
            ( |45| )
            ( |93| )
            ( |147| )
            ( |64| )
            ( |90| )
            ( |125| )
            ( |149| )
            ( |145| )
            ( |111| )
            ( |126| )
            ( |9| )
            ( |146| )
            ( |38| )
            ( |97| )
            ( |103| )
            ( |6| )
            ( |122| )
            ( |34| )
            ( |18| )
            ( |35| )
            ( |96| )
            ( |86| )
            ( |116| )
            ( |29| )
            ( |59| )
            ( |118| )
            ( |102| )
            ( |26| )
            ( |66| )
            ( |17| )
            ( |74| )
            ( |94| )
            ( |5| )
            ( |114| )
            ( |128| )
            ( |1| )
            ( |75| )
            ( |47| )
            ( |141| )
            ( |58| )
            ( |65| )
            ( |100| )
            ( |63| )
            ( |12| )
            ( |53| )
            ( |25| )
            ( |106| )
            ( |136| )
            ( |15| )
            ( |82| )
            ( |22| )
            ( |117| )
            ( |2| )
            ( |80| )
            ( |79| )
            ( |139| )
            ( |7| )
            ( |81| )
            ( |129| )
            ( |19| )
            ( |52| )
            ( |87| )
            ( |115| )
            ( |132| )
            ( |140| )
            ( |88| )
            ( |109| )
            ( |62| )
            ( |73| )
            ( |46| )
            ( |24| )
            ( |69| )
            ( |101| )
            ( |110| )
            ( |16| )
            ( |95| )
            ( |148| )
            ( |76| )
            ( |135| )
            ( |142| )
            ( |89| )
            ( |50| )
            ( |72| )
            ( |41| )
            ( |39| )
            ( |42| )
            ( |56| )
            ( |51| )
            ( |57| )
            ( |127| )
            ( |83| )
            ( |121| )
            ( |33| )
            ( |32| )
            ( |23| )
    ).
  ENDMETHOD.
ENDCLASS.
